const AdminControlerGestion = require('./controllers/AdminControlerGestion')
const adminControler = require('./controllers/adminControler')
const adminControler2 = require('./controllers/adminControler2')
const AuthController = require('./controllers/AuthController')
const AuthControllerPolicy = require('./policies/AuthControllerPolicy')
const DocDashboardController = require('./controllers/DocDashboardController')

module.exports = (app) => {
  app.post('/', AuthController.login)
  app.post('/register', AuthControllerPolicy.register, AuthController.register)
  app.post('/forgotpw', AuthController.forgotpw)
  app.post('/resetpw', AuthController.resetpw)
  app.get('/admin/novalid/', adminControler.index)
  app.get('/admin/valid/', adminControler2.index)
  app.post('/admin/validateUser', AdminControlerGestion.validateUser)
  app.post('/admin/deleteUser', AdminControlerGestion.deleteUser)
  app.post('/admin/desactivateUser', AdminControlerGestion.desactivateUser)
  app.get('/doc/patients', DocDashboardController.recoverPatients)
  app.post('/DOCdashboard', DocDashboardController.createMF)
  app.post('/DOCdashboard/showPatient', DocDashboardController.showPatient)
  app.post('/DOCdashboard/savePersInfo', DocDashboardController.savePersInfo)
  // app.post('/DOCdashboard/saveBioInfo', DocDashboardController.saveBioInfo)
  // app.post('/DOCdashboard/saveAntInfo', DocDashboardController.saveAntInfo)
  // app.post('/DOCdashboard/saveDepiInfo', DocDashboardController.saveDepiInfo)
}
